-- GCP 社員の給与を PDF（GCP管理名簿）の「給与」列（単位：万円）に合わせて設定。
-- 1=張宏亮 25万, 2=李帥虎 20万, 3=周皞 27万, 4=邢夢 20万, 5=孫培策 27万, 6=李景冬 32万,
-- 7=姚星孜 20万, 8=林広楠 20万, 9=張允僑 20万, 10=邵勝楠 28万, 11=胡卉 20万, 12=張永康 25万, 13=徐胤程 20万, 14=李衛芹 42万
-- 形式: description「基本給X万、社会保険加入、雇用保険加入」+ payrollConfig

UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給25万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":250000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP001';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP002';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給27万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":270000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP003';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP004';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給27万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":270000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP005';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給32万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":320000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP006';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP007';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP008';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP009';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給28万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":280000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP010';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP011';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給25万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":250000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP012';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給20万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":200000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP013';
UPDATE employees SET payload = jsonb_set(payload, '{salaries}', '[{"startDate":"2024-01-01","description":"基本給42万、社会保険加入、雇用保険加入","payrollConfig":{"baseSalary":420000,"socialInsurance":true,"employmentInsurance":true}}]'::jsonb) WHERE company_code = 'GCP' AND payload->>'code' = 'GCP014';
